# Generated by Django 3.0.5 on 2020-04-21 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='palyed',
            new_name='played',
        ),
    ]
